export const interests = [
  'Reading',
  'Writing',
  'Coding',
  'Gaming',
  'Cooking',
  'Baking',
  'Photography',
  'Videography',
  'Music',
  'Playing an instrument',
  'Singing',
  'Dancing',
  'Drawing',
  'Painting',
  'Sculpting',
  'Hiking',
  'Camping',
  'Traveling',
  'Learning new languages',
  'History',
  'Science',
  'Astronomy',
  'Philosophy',
  'Psychology',
  'Yoga',
  'Meditation',
  'Martial arts',
  'Playing sports',
  'Watching sports',
  'Movies',
  'TV shows',
  'Anime',
  'Documentaries',
  'Board games',
  'Card games',
  'Puzzles',
  'Volunteering',
  'Learning new skills',
  'DIY projects',
  'Carpentry',
  'Gardening',
  'Astronomy',
  'Web development',
  'Machine learning',
  'Artificial intelligence',
  'Robotics',
  'Electronics',
  'Cars',
  'Motorcycles',
  'Bicycles',
  'Fashion',
  'Interior design',
  'Makeup',
  'Hair styling',
  'Playing an instrument',
  'Composing music',
  'Playing video games',
  'Building video games',
  'Building computers',
  'Reading comics',
  'Watching anime',
  'Cosplay',
  'Playing role-playing games',
  'Learning about mythology',
  'Investing',
  'Personal finance',
  'Entrepreneurship',
  'Stock market',
  'Cryptocurrency',
  'Astronomy',
  'Astrophysics',
  'Ecology',
  'Climate change',
  'Animal welfare',
  'Space exploration',
  'Learning about different cultures',
  'Traveling to new countries',
  'Foreign languages',
  'Public speaking',
  'Debating',
  'Leadership',
  'Critical thinking',
  'Problem solving',
  'Playing chess',
  'Playing poker',
  'Magic tricks',
  'Playing the lottery',
  'Metal detecting',
  'Urban exploration',
  'Learning about history',
  'Visiting museums',
  'Watching documentaries',
  'Reading biographies',
  'Learning about different religions',
  'Meditation',
  'Mindfulness',
  'Playing brain teasers',
  'Learning a new musical instrument',
  'Playing sports',
  'Watching live sports',
  'Extreme sports',
  'Participating in marathons',
  'Learning self-defense',
  'Practicing martial arts',
  'Going to the gym',
  'Yoga',
  'Pilates',
  'Healthy eating',
  'Cooking healthy meals',
  'Learning about nutrition',
  'Trying new foods',
  'Wine tasting',
  'Coffee brewing',
];
